#!/bin/bash

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/workspace.json
pip install git+https://github.com/raphi6/pandas-datareader.git@ea66d6b981554f9d0262038aef2106dda7138316
pip install pycryptodome pycryptodomex
